services:
  postgres:
    image: postgres:15
    container_name: twitter_postgres
    environment:
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: twitterpass
      POSTGRES_DB: twitterdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twitter -d twitterdb"]
      interval: 5s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7
    ports: ["6379:6379"]
    command: ["redis-server","--appendonly","yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 20
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports: ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [user-service, posts-service]

  user-service:
    build:
      context: .                           
      dockerfile: services/user/Dockerfile
    container_name: user_service
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://twitter:twitterpass@postgres:5432/twitterdb?sslmode=disable"
      # альтернативно, если сервис читает раздельные переменные:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: twitter
      DB_PASSWORD: twitterpass
      DB_NAME: twitterdb
      REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  notifications-service:
    build:
      context: .                           
      dockerfile: services/notifications/Dockerfile
    container_name: notifications_service
    environment:
      PORT: "8082"
      DATABASE_URL: "postgres://twitter:twitterpass@postgres:5432/twitterdb?sslmode=disable"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: twitter
      DB_PASSWORD: twitterpass
      DB_NAME: twitterdb
      REDIS_ADDR: redis:6379
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy

  posts-service:
    build:
      context: .
      dockerfile: services/post/Dockerfile
    container_name: post_service
    environment:
      PORT: "8081"
      DATABASE_URL: "postgres://twitter:twitterpass@postgres:5432/twitterdb?sslmode=disable"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: twitter
      DB_PASSWORD: twitterpass
      DB_NAME: twitterdb
      REDIS_ADDR: redis:6379
      REDIS_NOTIF_STREAM: "events:notifications"
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
